source ~/.zshrc.common
source ~/.zshrc.aliases
source ~/.zshrc.base16
source ~/.zshrc.autojump
source ~/.zshrc.ssh
source ~/.zshrc.prompt
source ~/.zshrc.vcs
source ~/.zshrc.golang
source ~/.zshrc.symlink
source ~/.zshrc.vagrant
source ~/.zshrc.vagrant-coreos
source ~/.zshrc.virtualbox
