source ~/.zshrc.common
source ~/.zshrc.vcs
source ~/.zshrc.aliases
source ~/.zshrc.autojump
source ~/.zshrc.vagrant
source ~/.zshrc.vagrant-coreos
source ~/.zshrc.virtualbox
source ~/.zshrc.ssh
source ~/.zshrc.prompt
